### ISSUE TITLE
Counterexample trace in Eclipse and variable names

### ISSUE THREAD

**Issue by AFifarek** [lgwagner/SpeAR#11]
If a variable name starts with an "int" the trace does not show the variable in the counterexample. It is properly included in the logic analysis.

This image below is missing "intruderThreat" and "intruderSafe"

![missing_intruder_vars](https://cloud.githubusercontent.com/assets/6787980/14541450/11975f2e-0258-11e6-9a51-ee3e31efa058.PNG)

This image below renamed the "intruderThreat" and "intruderSafe" to "truderThreat" and "truderSafe" to avoid this issue.

![intruder_vars_now_truder](https://cloud.githubusercontent.com/assets/6787980/14541621/d14cae6e-0258-11e6-8133-3c88915d1b67.PNG)

**Comment by lgwagner** [comment]
This was caused by some Lustre keyword renaming. In the past, any Spear name that started with a lustre keyword (for example "INTruder") would be renamed. When we post analysis results we use the names from the initial SpeAR model. We should probably keep track of any renaming, but this is a fairly large effort. 

Now I only rename exact keyword matches, and I have an additional validation to alert the user when they've selected a reserved name. Basically, it is not impossible to use a lustre keyword as a name, so no renaming should ever occur.
