### ISSUE TITLE
Renaming files

### ISSUE THREAD

**Issue by jendavis** [lgwagner/SpeAR#38]
It would be nice if doing a Refactor->Rename on a file took care of the file name, the spec name, and any references via spec calls and imports.

**Comment by lgwagner** [comment]
Imports will be impossible, I fear, due to the nature of how they work.

I'm surprised specification calls are not resolved. I'll investigate.

**Comment by manthonyaiello** [comment]
@lgwagner specification calls _are_ resolved, if one clicks on the name of the specification in the spec file after the keyword `Specification` and selects "Rename Element". 

I think what @jendavis wanted was for renaming the _file_ to automatically also rename the specification in the spec file, itself. A sort of one-stop-renaming, like you get in Eclipse for Java source files: rename the class in the package explorer, and the file name is also changed.

Based on your comments above, that's unlikely to be possible because of the way in which imports work.

I suggest marking "won't fix" and closing this, given your comments.

**Comment by lgwagner** [comment]
It will require some investigaiton to rename the name of the Specification element inside the file. We can leave this but it's likely wontfix, at least in the short term.
